# Site Info
title: p1zz4's blog
tagline: 'blog for recording'
description: '기록용 블로그 '
url: http://p1zz4.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: p1zz4
  description: Algorithm, NLP, Image Processing, Forensic, Webhacking, Reversing, etc  
  #gravatar:  # md5 hash of your email address
  contact:
    #linkedin:  
    github:    https://github.com/p1zz4
    facebook:  https://www.facebook.com/guswl1414159
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:guswl1414@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://p1zz4.github.io/public/img/sky.jpeg
  caption: 말하는 감자  
  
# Puglins
mathjax: true # whether support mathjax
#google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'p1zz4-github-io' # leave blank if you don't want disqus

